# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EK\'sFireBase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EK'sFireBase
pod 'Firebase/Core'
pod 'FirebaseUI/Auth'
pod 'Firebase/Database'
end
